# Generated by Django 3.0.8 on 2020-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('sports', 'SPORTS'), ('shoes', 'SHOES'), ('jerseys', 'JERSEYS'), ('kids', 'KIDS'), ('accessories', 'accessories')], default='sports', max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
